version: '3'
services:
  patriot:
    image: tarot13/patriot
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    ports:
     - "443:443"
    volumes:
     - /etc/patriot:/etc/patriot
    cap_add:
     - NET_ADMIN
    restart: unless-stopped
    environment:
     - SSL_DOMAIN=example.test
     - V2RAY_HTTP_WEBSOCKET_PATH=api
     - ACME_EMAIL=admin@example.test
    labels:
      xyz.ianli.patriot.role: "all"